// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwn7tOjdMv6q6cnxcumFvpiVjVRNJJako',
    appId: '1:1094236636788:web:28fdc9a7d82632ebdbb321',
    messagingSenderId: '1094236636788',
    projectId: 'travel-weather-app-bitcube',
    authDomain: 'travel-weather-app-bitcube.firebaseapp.com',
    storageBucket: 'travel-weather-app-bitcube.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCKA_IOgKu71bQEkTs7VT6VxbJwZsbgY',
    appId: '1:1094236636788:android:1fa7b8eee01473b7dbb321',
    messagingSenderId: '1094236636788',
    projectId: 'travel-weather-app-bitcube',
    storageBucket: 'travel-weather-app-bitcube.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmZaU5MNnjs7bHCJExLDxOnH3j9hYiTI',
    appId: '1:1094236636788:ios:2cc296d63694db73dbb321',
    messagingSenderId: '1094236636788',
    projectId: 'travel-weather-app-bitcube',
    storageBucket: 'travel-weather-app-bitcube.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );
}
